### ISSUE TITLE
modules not loading

### ISSUE THREAD

**Issue by GoodWillGustin** [njwilliams/MMM-PlaceInfo#1]
I got my API keys and set up the config file. When I launch MM, not only does the PlaceInfo module not load (when set to either top_center or bottom_center), but none of my modules will load besides top_left, top_center, and middle_center regions. I'm getting no errors in the terminal. Here is my config.js entry:

{
       module: 'MMM-PlaceInfo',
	position: 'top-center',
		config: {
	weatherAPIKey: "myopenweatherAPIkey",
	currencyAPIKey: "myfixer.ioAPIkey",
	currencyPrecision: 2,
	currencyRelativeTo: 'USD',
		places: [
	{
	title: "London",
	flag: "gb",
	currency: "GBP",
	timezone: "Europe/London",
	weatherID: "2643743",
	},
	{
	title: "Tokyo",
	flag: "jp",
	currency: "JPY",
	timezone: "Asia/Tokyo",
	weatherID: "1857910",
	}
			]
			}
	},

**Comment by njwilliams** [comment]
Apologies, never saw this issue and just going through updating the package now I see this problem. The actual error here is a magic-mirror weirdness. You used 'top-center' when you should've used 'top_center'. the magic mirror framework didn't understand where to place it, so nothing happened.

Once you've got the location on the screen fixed, then you also need:
  timeFormat: "HH:mm A"
in the MMM-PlaceInfo config due to a bug in the formatting. I'll fix it so that's not a requirement now that I'm back looking at this!
